/* *********************************************************************** *
 * project: org.matsim.*
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2008 by the members listed in the COPYING,        *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */

package de.mobilitystudio.gui;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.matsim.core.controler.Controler;

import de.mobilitystudio.run.RunMatsimDefault;
import de.mobilitystudio.run.RunRailsim;

public class MATSimGUI {
	private static final Logger log = LogManager.getLogger(Controler.class);

	public static void main(String[] args) {
		
		// This sets up the modern FlatLaf theme based on a command-line argument.
		// It defaults to the light theme if no argument is provided.
	    if (args.length > 1) {
	    	String themeClassName = args[1];
	    	if ("com.formdev.flatlaf.FlatDarkLaf".equalsIgnoreCase(themeClassName)) {
	    		com.formdev.flatlaf.FlatDarkLaf.setup();
	    	} else {
	    		// Default to light for any other theme (e.g., FlatLightLaf, system default)
	    		com.formdev.flatlaf.FlatLightLaf.setup();
	    	}
	    } else {
	    	// Fallback to the default light theme if the argument is missing.
	    	com.formdev.flatlaf.FlatLightLaf.setup();
	    }

	    // This code makes the application feel more native on macOS.
	    String os = System.getProperty("os.name").toLowerCase();
	    if (os.contains("mac")) {
	        System.setProperty("apple.laf.useScreenMenuBar", "true");
	        System.setProperty("apple.awt.application.name", "MATSim Config Editor");
	        System.setProperty("apple.awt.application.appearance", "system");
	    }

	    if (args.length > 0) {
	    	String setup = args[0];
	    	log.info("Launching MATSim GUI for setup: " + setup);
	    	
	    	if (setup.equalsIgnoreCase("default")) {
	    		GuiWithConfigEditor.show("MATSim GUI for a default setup", RunMatsimDefault.class );
	    	
	    	} else if (setup.equalsIgnoreCase("railsim")) {
	    		GuiWithConfigEditor.show("MATSim GUI for railsim", RunRailsim.class );
	    	
	    	} else {
	    		log.error("Unknown setup argument: " + setup + ". Available options are 'default' and 'railsim'. "
	    				+ "Launching default setup.");
	    		GuiWithConfigEditor.show("MATSim GUI for a default setup", RunMatsimDefault.class );
	    	}
	    } else {
	    	// No command line arguments: launch the GUI with default setups.
			GuiWithConfigEditor.show("MATSim GUI for a default setup", RunMatsimDefault.class );
	    }

	}

	//	The jar file is generated by "mvn package".  Note that the pom.xml refers at some point to this class here. 

}
